dist: trusty
sudo: required

language: node_js
node_js:
- '7'
# [- Your NodeJS version]

branches:
  only:
    - master
    - dev
  # - Your branch name

deploy:
  provider: heroku
  app:
    master: polyhedron
    #Your branch name: Your heroku application name
    dev: polyhedron-team
  api_key:
    master:
      secure: nD6SI04xOLgJ8TAPbTUb5lvgVGGhc7wMtiryq6DjtlWrGLJOiLmlXrJadfbzt2+qQDqL4IJIlVlDwl4CP1mDJlMormoOt+UpNtCGVPlHP9VFdDonDadUDgUE5eNmh5A3cOEO/CnXWCbc1nK+nOgTsN6wwBdKb+7fPjSmqpLkIhW/HT/FssLIShjPA+Tr7BVocGMeilb2Z8tsQjxFCDTzIUpviy2ITVPmWg/wHg3S4IiQbw19CIObCktxAgDhhUuL0FfCzzL/9Hbj+hzI5PbMFEXKmxnK3T3B7Dj4w7ef5wDPV5EShbV6yN7urOU3TNfJK4asGRhQsdymP9HgCxr3I5lWPlrHHC/ETFLH5ngjqYmoNuZLw+M5TjB6iutkif+7uK0MBrY5A8D3tTdtcuQb4dTymwRL1nuy75dUZCnZaErRAP+k8Iqwk3a3Fd1eG8E/AikDanG1xuL6m0CXarrdYmZvPD0dS4E4fD5pADte8VsWd0q3gTHCrtQOXdj0TUg6K6imQ3Rubvfq0D+3lbT9W/rQdd2QKH92dybarchxNQZne8hKVZDXwj/MWAKxWsNl6yVsbVeUPwygDl8ZOY1pU48OxREzbq+fvPy3dg3idxGhrmMplu9+aFK6+dZfHqt/B2O9png9kUkt+YlzRAwiGUpdtZih/ApOtRdD2SLMwLM=
    dev:
#      secure: ZhmYHEvvoIC6Mr9VN4oaUQqaDIyTCV5ae79wJCBhljMnF+axgGo/d3ednlQtJYUt7C0cNgMU52WpquVqy6tXbPdtt7MtQk7FZIkV19AL05yeGNngzzAp/QeCxP+Nyaa4jrqx+8PbH7qYa29Nk+CDtgOsQfHhwxg0s4BX0S1KH1NkTSu24Uif3SCbnnN8rTcRpfOQFt9RLoyaYR0rzNgKyH9ORh99hDWFdx97fYnCSPhK09CqkeoREIBeJOeV2cyKscClxhy9ab7xSAAUKiK5Ml5WEBpt2PkQPw9hJxc/gPvAYXjrjocI4FI8lub4sMyiBYulPvpEqVPT+pQmEgj7ECYMhsJKeQyYB6X6W9bvWsP+7I/CoWRHPdX1c3d4QUR5p/F9cczOb0wVuNF3pQvhhbQcXPLOGutTR5pSOApybKG39i+OJy+2tSAdy60BbEX6uBLXSJZTMksvKezhGOfLVazZ/vOeTNds3K2K6ZJThQXqnuZfjD29pSA4tlRr4fHdPYu8wAO4++t3WN1/0Gb64DwzjDpzsZJewRkAttbroLmc2p0AZmrbesQj130YtGFYMRLWo3HAIjJIn5pOiietiXdtJ2aorUduTtL0IR+wrpKfjQVf1CWJVM7pcmWho+wehxl3RFCKrxTZ+Nwtun+NwUORgD8cfDIe2kySElQ+vdg=
       secure: C5GDqWsWzbd5oTmw1M8QkABlsaf0x3t6TR5jNGOVkGPMkTnJAApqY4jG7Msn+UcsUuS3FoaB2Sl4+ceM+CZEn8SNIv5lpgr9PgRu6lb7fS2U9qP5NBArvHk/TiiBC6KJSGWBBpjxTmGjl1F1VQDsv/nZXqrzmyBAPHkhZHtNpgJZ0ZRDGmWbtT3MFyHjAhDGiX9yO5J/DURET3iKCCutrFaPfZrnIHn5OcON7Nao8rsUwMQxfWoGhWb8SJeK+9ImWrEOHKE+A1q+JW7XZcOhvpy2Yb9uw+OwdK4IlkRkdCij0ckmUf5SkmwSYxFylOL5VnYrKyXUqc75xcAh/WUgQJRgOR7lyXT6T3IdrUnZJgNvIqL35/cpkZYDN2q9+LulV24wAHGKPtf/S9/xppmYyK4tDN0AmwrM4xltlZB030A/fdfxD0bG+v+5Ye9qvhR8Onp0RVzyDIj3idgGRqYnE+y4ZNKNkEP5E1PALblwJ2Zgfx48o3iDSw4Lvzc9MEC74vGSu2oIwoAI6cFHZohrIZto77zPTjWLo0H/RQFntdeTW8IJKa398BgqbSQhJmi7tPyZlWDi8lVb3MJIN+kqOjPQOZoJXByirkh6fQO/UO7ohFg4tJBdZfX9AjxHalrGv4ckrPeOdIqBYuCEWsJ5L9FyyiJE4Snnm6vi/G4kaeA=

  # Your branch name:
# secure: Your api secret
